/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/spaceship-model-glass.glb 
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { ColorShiftMaterial } from "./Light";
import { useThree } from "@react-three/fiber";
import { MeshPhysicalMaterial } from "three";
import { mobileBreakPoint } from "@sharedData/index.ts";
import { useWindowDimensions } from "@hooks/useWindowDimensions";

const glassMaterial = new MeshPhysicalMaterial({
  metalness: 0,
  depthTest: false,
  depthWrite: false,
  transmission: 1,
  thickness: 0,
  roughness: 0,
  envMapIntensity: 0.3,
});

const renderOrders = {
  glass: 1,
  ship: 2,
  shipPanels: 3,
  consoleBack: 4,
  console: 5,
  consoleFront: 6,
  consoleFrontDetails: 7,
  consoleLightRings: 8,
};

export function Model(props) {
  const { clock } = useThree();
  const { width } = useWindowDimensions();
  const shipTexture = useTexture("/baked/baked-ship-8192.jpg");
  shipTexture.flipY = false;
  const consoleTexture = useTexture("/baked/baked-console-4096.jpg");
  consoleTexture.flipY = false;
  // Note: Splitting the model like this is necessary in order to work around
  //       the limitations of ejecting from depthTest. Certain parts of the model
  //       must be explicitly rendered on top of others.
  // Note: Splitting the console into center/side parts is necessary for removing
  //       the sides on mobile
  const {
    console,
    consoleBack,
    consoleFront,
    consoleFrontDetails,
    consoleLightRings,
    consoleSides,
    consoleBackSides,
    consoleFrontSides,
    consoleFrontDetailsSides,
    consoleLightRingsSides,
    glass,
    ship,
    shipPanels,
  } = useGLTF("/baked/spaceship.glb").nodes;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={glass.geometry}
        material={glassMaterial}
        renderOrder={renderOrders.glass}
      ></mesh>

      {/* Ship */}
      <mesh geometry={ship.geometry} renderOrder={renderOrders.ship}>
        <meshBasicMaterial map={shipTexture} depthTest={false} />
      </mesh>
      <mesh
        geometry={shipPanels.geometry}
        renderOrder={renderOrders.shipPanels}
      >
        <meshBasicMaterial map={shipTexture} depthTest={false} />
      </mesh>

      {/* Console */}
      <group position={[0, 0.4, 0]}>
        {/* Console Center */}
        <mesh
          geometry={consoleBack.geometry}
          renderOrder={renderOrders.consoleBack}
        >
          <meshBasicMaterial map={consoleTexture} depthTest={false} />
        </mesh>
        <mesh geometry={console.geometry} renderOrder={renderOrders.console}>
          <meshBasicMaterial map={consoleTexture} depthTest={false} />
        </mesh>
        <mesh
          geometry={consoleFront.geometry}
          renderOrder={renderOrders.consoleFront}
        >
          <meshBasicMaterial map={consoleTexture} depthTest={false} />
        </mesh>
        <mesh
          geometry={consoleFrontDetails.geometry}
          renderOrder={renderOrders.consoleFrontDetails}
        >
          <meshBasicMaterial map={consoleTexture} depthTest={false} />
        </mesh>
        <mesh
          geometry={consoleLightRings.geometry}
          renderOrder={renderOrders.consoleLightRings}
        >
          <colorShiftMaterial
            emissive={[1, 1, 1]}
            emissiveIntensity={30}
            color="green"
            time={clock.elapsedTime}
            speed={0.6}
            depthWrite={false}
            depthTest={false}
          />
        </mesh>

        {/* Console Sides */}
        {width > mobileBreakPoint ? (
          <>
            <mesh
              geometry={consoleBackSides.geometry}
              renderOrder={renderOrders.consoleBack}
            >
              <meshBasicMaterial map={consoleTexture} depthTest={false} />
            </mesh>
            <mesh
              geometry={consoleSides.geometry}
              renderOrder={renderOrders.console}
            >
              <meshBasicMaterial map={consoleTexture} depthTest={false} />
            </mesh>
            <mesh
              geometry={consoleFrontSides.geometry}
              renderOrder={renderOrders.consoleFront}
            >
              <meshBasicMaterial map={consoleTexture} depthTest={false} />
            </mesh>
            <mesh
              geometry={consoleFrontDetailsSides.geometry}
              renderOrder={renderOrders.consoleFrontDetails}
            >
              <meshBasicMaterial map={consoleTexture} depthTest={false} />
            </mesh>
            <mesh
              geometry={consoleLightRingsSides.geometry}
              renderOrder={renderOrders.consoleLightRings}
            >
              <colorShiftMaterial
                emissive={[1, 1, 1]}
                emissiveIntensity={30}
                color="green"
                time={clock.elapsedTime}
                speed={0.6}
                depthWrite={false}
                depthTest={false}
              />
            </mesh>
          </>
        ) : null}
      </group>
    </group>
  );
}

useGLTF.preload("/baked/spaceship.glb");
